networks:
  net:
    driver: bridge

services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1
    ports:
      - "5433:5432"
